#!/bin/sh

curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/analise-gerente    -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/analise-gerente-vinculo    -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/aprovacao-rollback -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/autocadastro-autenticacao  -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/autocadastro-autenticacao-rollback -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/autocadastro-cliente   -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/autocadastro-cliente-rollback  -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/autocadastro-gerente   -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/autocadastro-gerente-conta -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/autocadastro-gerente-conta-rollback    -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/autocadastro-gerente-rollback  -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/conta-inserir  -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/conta-inserir-read -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/gerar-senha-cliente    -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/movimentacao-inserir   -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/nova-conta -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/nova-conta-rollback    -u "guest:guest" --data-raw '{"durable": true}'
curl -X DELETE http://host.docker.internal:15672/api/queues/%2F/nova-senha-rollback    -u "guest:guest" --data-raw '{"durable": true}'

